#!/usr/bin/python

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)
GPIO.setup(11,GPIO.OUT)
GPIO.setup(12,GPIO.OUT)

time.sleep(1)
GPIO.output(11,GPIO.HIGH)
GPIO.outupt(12,GPIO.HIGH)
time.sleep(2)

GPIO.output(11,GPIO.HIGH)
GPIO.output(12,GPIO.OUT)
time.sleep(1)

GPIO.output(11,GPIO.HIGH)
GPIO.output(12,GPIO.HIGH)

GPIO.cleanup()
